#!/usr/bin/env python3
"""
Script to generate the reference navigation with type hints visualization.
This script is used by the mkdocs-gen-files plugin to generate the navigation.
"""

from pathlib import Path

import mkdocs_gen_files

# Configuration
SDK_DIR = Path("src/openmisp/sdk")
DOCS_DIR = Path("docs/api-reference")
EXCLUDED_FILES = ["__init__.py", "__pycache__", "_models.py"]
EXCLUDED_MODULES = [f.rstrip(".py") for f in EXCLUDED_FILES]

# Create the API reference index
index_path = Path("api-reference", "index.md")
with mkdocs_gen_files.open(index_path, "w") as index_file:
    index_file.write("# API Reference\n\n")
    index_file.write(
        "This section contains the automatically generated API reference documentation for the OpenMISP.\n\n"
    )
    index_file.write(
        "The documentation is generated directly from the source code using docstrings and type hints.\n\n"
    )
    index_file.write("## Modules\n\n")

# Process each module
for module_path in sorted(SDK_DIR.glob("*.py")):
    module_name = module_path.stem

    # Skip excluded modules
    if module_name in EXCLUDED_MODULES or module_name.startswith("_"):
        continue

    # Create the documentation file
    doc_path = Path("api-reference", f"{module_name}.md")

    # Add to the index
    with mkdocs_gen_files.open(index_path, "a") as index_file:
        title = module_name.replace("_", " ").title()
        index_file.write(f"- [{title}]({module_name}.md)\n")

    # Create the module documentation
    with mkdocs_gen_files.open(doc_path, "w") as doc_file:
        title = module_name.replace("_", " ").title()
        doc_file.write(f"# {title} API Reference\n\n")
        doc_file.write(
            f"This page contains the automatically generated API reference for the {module_name} module.\n\n"
        )
        doc_file.write("## Module Reference\n\n")
        doc_file.write(f"::: openmisp.sdk.{module_name}\n")
        doc_file.write("    options:\n")
        doc_file.write("      show_root_heading: true\n")
        doc_file.write("      show_source: true\n")
        doc_file.write("      group_by_category: true\n")
        doc_file.write("      show_submodules: true\n")
        doc_file.write("      merge_init_into_class: true\n")
        doc_file.write("      show_signature: true\n")
        doc_file.write("      show_bases: true\n")
        doc_file.write('      filters: ["!^_[^_]"]\n')

# Create a .gitignore file to ignore the generated files
with mkdocs_gen_files.open(".gitignore", "w") as gitignore:
    gitignore.write("# Generated by gen_ref_nav.py\n")
    gitignore.write("api-reference/\n")
